# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c1a39944a4ab6bdd6e4428ccceb028b"
name = "new"
application_url = "https://appreciate-explosion-abc-allows.trycloudflare.com"
embedded = true
handle = "new-270"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "bulk_operations/finish" ]
  uri = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_metaobjects,read_products,write_products"

[auth]
redirect_urls = [
  "https://appreciate-explosion-abc-allows.trycloudflare.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
