# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6f9d8710bcea15a9a7814c24bb5404be"
application_url = "https://deviation-phd-surgery-lands.trycloudflare.com/"
embedded = true
name = "new"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [ "bulk_operations/finish" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [ "app_subscriptions/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_products"

[auth]
redirect_urls = [
  "https://deviation-phd-surgery-lands.trycloudflare.com/auth/callback",
  "https://deviation-phd-surgery-lands.trycloudflare.com/auth/shopify/callback",
  "https://deviation-phd-surgery-lands.trycloudflare.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
