export const OPERATION_LIFECYCLE_STATES = Object.freeze({
  DRAFT: "DRAFT",
  PREVIEWED: "PREVIEWED",
  TARGET_FREEZING: "TARGET_FREEZING",
  TARGET_FROZEN: "TARGET_FROZEN",
  PLANNING: "PLANNING",
  SCHEDULED_PENDING_QUEUE: "SCHEDULED_PENDING_QUEUE",
  SCHEDULED_QUEUED: "SCHEDULED_QUEUED",
  PLANNED: "PLANNED",
  QUEUED: "QUEUED",
  PAUSED: "PAUSED",
  SUSPENDED: "SUSPENDED",
  WAITING_FOR_SHOPIFY_SLOT: "WAITING_FOR_SHOPIFY_SLOT",
  EXECUTING: "EXECUTING",
  RECONCILE_SUBMITTED: "RECONCILE_SUBMITTED",
  SHOPIFY_BULK_SUBMITTED: "SHOPIFY_BULK_SUBMITTED",
  SHOPIFY_RUNNING: "SHOPIFY_RUNNING",
  SHOPIFY_COMPLETED: "SHOPIFY_COMPLETED",
  INGESTING_RESULTS: "INGESTING_RESULTS",
  VERIFYING: "VERIFYING",
  VERIFICATION_TIMEOUT: "VERIFICATION_TIMEOUT",
  MIRROR_UPDATING: "MIRROR_UPDATING",
  COMPLETED: "COMPLETED",
  PARTIAL_FAILED: "PARTIAL_FAILED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  UNDO_QUEUED: "UNDO_QUEUED",
  UNDO_RUNNING: "UNDO_RUNNING",
  UNDO_COMPLETED: "UNDO_COMPLETED",
  ROLLING_BACK: "ROLLING_BACK",
  ROLLED_BACK: "ROLLED_BACK",
  ROLLBACK_FAILED: "ROLLBACK_FAILED",
});

const ALLOWED_TRANSITIONS = Object.freeze({
  DRAFT: ["PREVIEWED", "TARGET_FREEZING", "CANCELLED"],
  PREVIEWED: ["TARGET_FREEZING", "CANCELLED"],
  TARGET_FREEZING: ["TARGET_FROZEN", "FAILED", "CANCELLED"],
  TARGET_FROZEN: ["PLANNING", "CANCELLED"],
  PLANNING: ["SCHEDULED_PENDING_QUEUE", "SCHEDULED_QUEUED", "PLANNED", "FAILED", "CANCELLED"],
  SCHEDULED_PENDING_QUEUE: ["SCHEDULED_QUEUED", "FAILED", "CANCELLED"],
  SCHEDULED_QUEUED: ["TARGET_FREEZING", "QUEUED", "FAILED", "CANCELLED"],
  PLANNED: ["QUEUED", "CANCELLED"],
  QUEUED: ["PAUSED", "SUSPENDED", "WAITING_FOR_SHOPIFY_SLOT", "EXECUTING", "CANCELLED", "FAILED"],
  PAUSED: ["QUEUED", "CANCELLED", "FAILED"],
  SUSPENDED: ["QUEUED", "EXECUTING", "CANCELLED", "FAILED"],
  WAITING_FOR_SHOPIFY_SLOT: ["QUEUED", "EXECUTING", "CANCELLED", "FAILED"],
  EXECUTING: ["SUSPENDED", "RECONCILE_SUBMITTED", "SHOPIFY_BULK_SUBMITTED", "FAILED", "CANCELLED"],
  RECONCILE_SUBMITTED: ["SHOPIFY_RUNNING", "SHOPIFY_COMPLETED", "FAILED", "CANCELLED"],
  SHOPIFY_BULK_SUBMITTED: ["SHOPIFY_RUNNING", "FAILED", "CANCELLED"],
  SHOPIFY_RUNNING: ["SHOPIFY_COMPLETED", "FAILED", "CANCELLED"],
  SHOPIFY_COMPLETED: ["INGESTING_RESULTS", "VERIFYING", "MIRROR_UPDATING", "COMPLETED", "PARTIAL_FAILED", "FAILED"],
  INGESTING_RESULTS: ["VERIFYING", "MIRROR_UPDATING", "COMPLETED", "PARTIAL_FAILED", "FAILED"],
  VERIFYING: ["VERIFICATION_TIMEOUT", "MIRROR_UPDATING", "COMPLETED", "PARTIAL_FAILED", "FAILED"],
  VERIFICATION_TIMEOUT: ["VERIFYING", "FAILED", "ROLLING_BACK"],
  MIRROR_UPDATING: ["COMPLETED", "PARTIAL_FAILED", "FAILED"],
  COMPLETED: ["UNDO_QUEUED", "ROLLING_BACK"],
  PARTIAL_FAILED: ["UNDO_QUEUED", "ROLLING_BACK"],
  FAILED: ["UNDO_QUEUED", "ROLLING_BACK"],
  CANCELLED: [],
  UNDO_QUEUED: ["UNDO_RUNNING", "CANCELLED", "FAILED"],
  UNDO_RUNNING: ["UNDO_COMPLETED", "ROLLED_BACK", "ROLLBACK_FAILED", "FAILED", "PARTIAL_FAILED", "CANCELLED"],
  UNDO_COMPLETED: [],
  ROLLING_BACK: ["ROLLED_BACK", "ROLLBACK_FAILED", "FAILED"],
  ROLLED_BACK: [],
  ROLLBACK_FAILED: [],
});

export function canTransitionOperationState(fromState, toState) {
  const from = String(fromState || "").toUpperCase();
  const to = String(toState || "").toUpperCase();
  const allowed = ALLOWED_TRANSITIONS[from] || [];
  return allowed.includes(to);
}

export function normalizeLifecycleToEditExecutionState(value) {
  const v = String(value || "").trim().toUpperCase();
  if (
    ["DRAFT", "PREVIEWED", "TARGET_FREEZING", "TARGET_FROZEN", "PLANNING", "PLANNED"].includes(v)
  ) return "PLANNED";
  if (v === "PAUSED") return "PAUSED";
  if (["SUSPENDED", "SCHEDULED_PENDING_QUEUE", "SCHEDULED_QUEUED", "QUEUED", "UNDO_QUEUED", "WAITING_FOR_SHOPIFY_SLOT"].includes(v)) return "QUEUED";
  if (v === "EXECUTING") return "DISPATCHING";
  if (["RECONCILE_SUBMITTED", "SHOPIFY_BULK_SUBMITTED", "SHOPIFY_RUNNING"].includes(v)) return "AWAITING_SHOPIFY";
  if (["SHOPIFY_COMPLETED", "INGESTING_RESULTS", "VERIFYING", "MIRROR_UPDATING", "UNDO_RUNNING", "ROLLING_BACK"].includes(v)) {
    return "FINALIZING";
  }
  if (v === "VERIFICATION_TIMEOUT") return "VERIFICATION_TIMEOUT";
  if (v === "ROLLED_BACK") return "ROLLED_BACK";
  if (v === "ROLLBACK_FAILED") return "ROLLBACK_FAILED";
  if (["COMPLETED", "UNDO_COMPLETED"].includes(v)) return "COMPLETED";
  if (v === "PARTIAL_FAILED") return "PARTIAL";
  if (v === "FAILED") return "FAILED";
  if (v === "CANCELLED") return "CANCELLED";
  return "UNKNOWN";
}
