//utils/productExportUtils.js
export const fieldMappings = {
  ProductID: "id",
  ProductTitle: "title",
  ProductDescription: "descriptionHtml",
  Vendor: "vendor",
  ProductType: "productType",
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  PublishedAt: "publishedAt",
  Handle: "handle",
  TemplateSuffix: "templateSuffix",
  Tags: "tags",
  Status: "status",
  SeoTitle: "seo.title",
  SeoDescription: "seo.description",
  ProductCategory: "category.name",
  TotalInventory: "totalInventory",

  VariantID: "variants.id",
  VariantTitle: "variants.title",
  Price: "variants.price",
  SKU: "variants.sku",
  Barcode: "variants.barcode",
  InventoryQuantity: "variants.inventoryQuantity",
  InventoryPolicy: "variants.inventoryPolicy",
  RequiresShipping: "variants.inventoryItem.requiresShipping",
  Weight: "variants.inventoryItem.measurement.weight.value",
  WeightUnit: "variants.inventoryItem.measurement.weight.unit",
  CountryOfOrigin: "variants.inventoryItem.countryCodeOfOrigin",
  HsTariffCode: "variants.inventoryItem.harmonizedSystemCode",
  Cost: "variants.inventoryItem.unitCost.amount",
  TaxCode: "variants.taxCode",
  Taxable: "variants.taxable",

  Option1: "variants.selectedOptions.0.value",
  Option2: "variants.selectedOptions.1.value",
  Option3: "variants.selectedOptions.2.value",

  ImageURL: "featuredMedia.preview.image.url",
  ImageAltText: "featuredMedia.preview.image.altText",
  ImageID: "featuredMedia.id",
};
