ALTER TYPE "TargetSnapshotTargetType" ADD VALUE IF NOT EXISTS 'PRODUCT_OPTION';
ALTER TYPE "TargetSnapshotTargetType" ADD VALUE IF NOT EXISTS 'COLLECTION_MEMBERSHIP';
ALTER TYPE "TargetSnapshotTargetType" ADD VALUE IF NOT EXISTS 'INVENTORY_LEVEL';
