export const RULE_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  DELETED: "DELETED",
});

export const RUN_STATUS = Object.freeze({
  TARGET_FREEZE_QUEUED: "TARGET_FREEZE_QUEUED",
  TARGET_FREEZING: "TARGET_FREEZING",
  TARGET_FROZEN: "TARGET_FROZEN",
  EXECUTING: "EXECUTING",
  VERIFYING: "VERIFYING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  UNDO_PENDING: "UNDO_PENDING",
  UNDO_EXECUTING: "UNDO_EXECUTING",
});

export const ACTIVE_RUN_STATUSES = Object.freeze([
  RUN_STATUS.TARGET_FREEZE_QUEUED,
  RUN_STATUS.TARGET_FREEZING,
  RUN_STATUS.TARGET_FROZEN,
  RUN_STATUS.EXECUTING,
  RUN_STATUS.VERIFYING,
  RUN_STATUS.UNDO_PENDING,
  RUN_STATUS.UNDO_EXECUTING,
]);

export const OPERATION_TYPE = Object.freeze({
  AUTOMATIC_PRODUCT_RULE_RUN: "AUTOMATIC_PRODUCT_RULE_RUN",
});

export const OPERATION_SOURCE = Object.freeze({
  AUTOMATIC_RULE_RUN_NOW: "AUTOMATIC_RULE_RUN_NOW",
  AUTOMATIC_RULE_SCHEDULED: "AUTOMATIC_RULE_SCHEDULED",
});

export const OPERATION_STATUS = Object.freeze({
  TARGET_FREEZE_QUEUED: "TARGET_FREEZE_QUEUED",
  CANCELLED: "CANCELLED",
});

export const TARGET_FREEZE_COMMAND_STATUS = Object.freeze({
  PENDING: "PENDING",
});

export const TARGET_FREEZE_SOURCE_TYPE = Object.freeze({
  AUTOMATIC_PRODUCT_RULE: "AUTOMATIC_PRODUCT_RULE",
});

export const OUTBOX_STATUS = Object.freeze({
  PENDING: "PENDING",
});

export const PAUSE_POLICY = Object.freeze({
  FUTURE_ONLY: "FUTURE_ONLY",
  CANCEL_QUEUED: "CANCEL_QUEUED",
});

export const DELETE_POLICY = Object.freeze({
  BLOCK_FUTURE_RUNS: "SOFT_DELETE_BLOCK_FUTURE_RUNS",
  CANCEL_QUEUED: "SOFT_DELETE_AND_CANCEL_QUEUED",
});
