//frontend/Domain/products/list/constants.js
/* ===============================
   Operator Definitions
================================ */

const STRING_OPERATORS = [
  "contains",
  "does not contain",
  "equals",
  "does not equal",
  "starts with",
  "ends with",
  "is empty/blank",
  "is not empty",
];

const DATE_OPERATORS = [
  "is before",
  "is after",
];

const NUMBER_OPERATORS = ["<", ">", "=", "!="];

const ENUM_OPERATORS = ["is", "is not"];

/* ===============================
   Filter Configuration
================================ */

export const FILTER_CONFIG = {
  product: [
    {
      key: "title",
      label: "Title",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "vendor",
      label: "Vendor",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/vendor",
      operators: STRING_OPERATORS,
    },
    {
      key: "handle",
      label: "Handle (URL)",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "product_type",
      label: "Product Type",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/product_type",
      operators: STRING_OPERATORS,
    },
    {
      key: "collection",
      label: "Collection",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/collection",
      operators: ENUM_OPERATORS,
    },
    {
      key: "category",
      label: "Category",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/category",
      operators: ENUM_OPERATORS,
    },
    {
      key: "description",
      label: "Description",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "option_name_1",
      label: "Option 1 Name",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/option_name_1",
      operators: STRING_OPERATORS,
    },
    {
      key: "option_name_2",
      label: "Option 2 Name",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/option_name_2",
      operators: STRING_OPERATORS,
    },
    {
      key: "option_name_3",
      label: "Option 3 Name",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/option_name_3",
      operators: STRING_OPERATORS,
    },
    {
      key: "product_id",
      label: "Product ID",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "inventory_q",
      label: "Inventory Quantity",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "tag",
      label: "Tag",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/tag",
      operators: STRING_OPERATORS,
    },
    {
      key: "theme_template",
      label: "Theme Template",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "variant_count",
      label: "Variant Count",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "visible_online_store",
      label: "Visible on Online Store",
      type: "enum",
      isSearchable: false,
      operators: ["is"],
      values: ["true", "false"],
    },
    {
      key: "updated_at",
      label: "Date Updated",
      type: "date",
      isSearchable: false,
      operators: DATE_OPERATORS,
    },
    {
      key: "created_at",
      label: "Date Created",
      type: "date",
      isSearchable: false,
      operators: DATE_OPERATORS,
    },
    {
      key: "published_at",
      label: "Date Published",
      type: "date",
      isSearchable: false,
      operators: DATE_OPERATORS,
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      isSearchable: false,
      operators: ["is"],
      values: ["ACTIVE", "DRAFT", "ARCHIVED"],
    },
    {
      key: "googleShoppingEnabled",
      label: "Google Shopping Enabled",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["true", "false"],
    },
    {
      key: "googleShoppingAgeGroup",
      label: "Google Shopping Age Group",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["newborn", "infant", "toddler", "kids", "adult"],
    },
    {
      key: "googleShoppingCategory",
      label: "Google Shopping Category",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingCategory",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingColor",
      label: "Google Shopping Color",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingColor",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingCondition",
      label: "Google Shopping Condition",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["new", "used", "refurbished"],
    },
    {
      key: "googleShoppingCustomLabel0",
      label: "Google Shopping Custom Label 0",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingCustomLabel0",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingCustomLabel1",
      label: "Google Shopping Custom Label 1",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingCustomLabel1",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingCustomLabel2",
      label: "Google Shopping Custom Label 2",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingCustomLabel2",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingCustomLabel3",
      label: "Google Shopping Custom Label 3",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingCustomLabel3",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingCustomLabel4",
      label: "Google Shopping Custom Label 4",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingCustomLabel4",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingCustomProduct",
      label: "Google Shopping Custom Product",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["true", "false"],
    },
    {
      key: "googleShoppingGender",
      label: "Google Shopping Gender",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["male", "female", "unisex"],
    },
    {
      key: "googleShoppingMpn",
      label: "Google Shopping MPN",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingMpn",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingMaterial",
      label: "Google Shopping Material",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingMaterial",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingSize",
      label: "Google Shopping Size",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/googleShoppingSize",
      operators: STRING_OPERATORS,
    },
    {
      key: "googleShoppingSizeSystem",
      label: "Google Shopping Size System",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["US", "UK", "EU", "DE", "FR", "IT", "JP", "CN", "AU", "BR"],
    },
    {
      key: "googleShoppingSizeType",
      label: "Google Shopping Size Type",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["regular", "petite", "plus", "big and tall", "maternity"],
    },
    {
      key: "categoryAgeGroup",
      label: "Category Age Group",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/categoryAgeGroup",
      operators: STRING_OPERATORS,
    },
    {
      key: "categoryColor",
      label: "Category Color",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/categoryColor",
      operators: STRING_OPERATORS,
    },
    {
      key: "categoryFabric",
      label: "Category Fabric",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/categoryFabric",
      operators: STRING_OPERATORS,
    },
    {
      key: "categoryFit",
      label: "Category Fit",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/categoryFit",
      operators: STRING_OPERATORS,
    },
    {
      key: "categorySize",
      label: "Category Size",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/categorySize",
      operators: STRING_OPERATORS,
    },
    {
      key: "categoryTargetGender",
      label: "Category Target Gender",
      type: "enum",
      isSearchable: false,
      operators: ENUM_OPERATORS,
      values: ["male", "female", "unisex"],
    },
    {
      key: "categoryWaistRise",
      label: "Category Waist Rise",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/categoryWaistRise",
      operators: STRING_OPERATORS,
    },
  ],

  variant: [
    {
      key: "barcode",
      label: "Barcode",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "sku",
      label: "SKU",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "variant_title",
      label: "Variant Title",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "price",
      label: "Price",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "compare_at_price",
      label: "Compare-at Price",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "variant_inventory_q",
      label: "Variant Inventory Quantity",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "option_value_1",
      label: "Option 1 Value",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/option_value_1",
      operators: STRING_OPERATORS,
    },
    {
      key: "option_value_2",
      label: "Option 2 Value",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/option_value_2",
      operators: STRING_OPERATORS,
    },
    {
      key: "option_value_3",
      label: "Option 3 Value",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/option_value_3",
      operators: STRING_OPERATORS,
    },
    {
      key: "charge_tax",
      label: "Charge Tax",
      type: "enum",
      isSearchable: false,
      operators: ["is"],
      values: ["true", "false"],
    },
    {
  key: "seo_visibility",
  label: "Search Engine Visibility (SEO)",
  type: "enum",
  isSearchable: false,
  operators: ["is"],
  values: ["true", "false"],
},
    {
      key: "cost",
      label: "Cost",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "country_of_origin",
      label: "Country of Origin",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/country_of_origin",
      operators: STRING_OPERATORS,
    },
    {
      key: "hs_tariff_code",
      label: "HS Tariff Code",
      type: "string",
      isSearchable: false,
      operators: STRING_OPERATORS,
    },
    {
      key: "inventory_policy",
      label: "Inventory Out of Stock Policy",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/inventory_policy",
      operators: STRING_OPERATORS,
    },
    {
      key: "physical_product",
      label: "Physical Product",
      type: "enum",
      isSearchable: false,
      operators: ["is"],
      values: ["true", "false"],
    },
    {
      key: "profit_margin",
      label: "Profit Margin",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "track_quantity",
      label: "Track Quantity",
      type: "enum",
      isSearchable: false,
      operators: ["is"],
      values: ["true", "false"],
    },
    {
      key: "weight",
      label: "Weight",
      type: "number",
      isSearchable: false,
      operators: NUMBER_OPERATORS,
    },
    {
      key: "weight_unit",
      label: "Weight Unit",
      type: "string",
      isSearchable: true,
      api: "/api/products/filter-values/weight_unit",
      operators: STRING_OPERATORS,
    },
  ],
};

/* ===============================
   Helpers
================================ */

export const ALL_FILTERS = [
  ...FILTER_CONFIG.product,
  ...FILTER_CONFIG.variant,
];

export const getAllFilters = () => ALL_FILTERS;

export const getFilterByKey = (key) =>
  ALL_FILTERS.find((f) => f.key === key);
