export const TARGET_GRANULARITY = Object.freeze({
  PRODUCT: "PRODUCT",
  VARIANT: "VARIANT",
  PRODUCT_WITH_MATCHING_VARIANTS: "PRODUCT_WITH_MATCHING_VARIANTS",
});

export const TARGET_TYPE = Object.freeze({
  PRODUCT: "PRODUCT",
  VARIANT: "VARIANT",
});

export const TARGETING_MODE = Object.freeze({
  FROZEN_AT_CREATE: "FROZEN_AT_CREATE",
  DYNAMIC_AT_RUN: "DYNAMIC_AT_RUN",
  EXPLICIT_TARGETS: "EXPLICIT_TARGETS",
});

export const TARGET_SNAPSHOT_OWNER_TYPE = Object.freeze({
  EDIT_HISTORY: "EDIT_HISTORY",
  EXPORT_JOB: "EXPORT_JOB",
  RECURRING_EDIT_RUN: "RECURRING_EDIT_RUN",
  AUTOMATIC_PRODUCT_RULE_RUN: "AUTOMATIC_PRODUCT_RULE_RUN",
});
