export const TARGET_SNAPSHOT_OWNER_TYPES = Object.freeze({
  EDIT_HISTORY: "EDIT_HISTORY",
  EXPORT_JOB: "EXPORT_JOB",
  RECURRING_EDIT_RUN: "RECURRING_EDIT_RUN",
  AUTOMATIC_PRODUCT_RULE_RUN: "AUTOMATIC_PRODUCT_RULE_RUN",
  SCHEDULED_EXPORT_RUN: "SCHEDULED_EXPORT_RUN",
  RECURRING_EDIT: "RECURRING_EDIT",
  AUTOMATIC_PRODUCT_RULE: "AUTOMATIC_PRODUCT_RULE",
});

export const TARGET_TYPES = Object.freeze({
  PRODUCT: "PRODUCT",
  VARIANT: "VARIANT",
});

export const TARGET_GRANULARITIES = Object.freeze({
  PRODUCT: "PRODUCT",
  VARIANT: "VARIANT",
  PRODUCT_WITH_MATCHING_VARIANTS: "PRODUCT_WITH_MATCHING_VARIANTS",
});

export const TARGETING_MODES = Object.freeze({
  STATIC_AT_SCHEDULE_CREATE: "STATIC_AT_SCHEDULE_CREATE",
  DYNAMIC_AT_RUN: "DYNAMIC_AT_RUN",
  STATIC: "STATIC",
});
