export const DEFAULT_PRICING_PLANS = Object.freeze([
  {
    key: "STARTER",
    name: "Starter",
    description: "For small stores getting started with basic bulk editing.",
    price: null,
    compareAtPrice: null,
    features: [
      "10 product limit for edits, export, and import",
      "Unlimited manual edits during development stores if applicable",
      "Basic bulk edit tools",
      "Basic product filters",
      "Email support",
    ],
    buttonText: "Current plan",
    buttonVariant: "secondary",
    isFree: true,
    popular: false,
    isCurrent: true,
    highlight: "No monthly charge",
  },
  {
    key: "BASIC_MONTHLY",
    name: "Basic",
    description: "For stores that need faster bulk editing workflows.",
    price: 25,
    compareAtPrice: null,
    features: [
      "Unlimited products per task",
      "60-day bulk edit history",
      "1 inventory sync job",
      "Scheduled edits",
      "Recurring edits",
      "Edit multiple fields at once",
      "Export and import support",
    ],
    buttonText: "Choose Basic",
    buttonVariant: "primary",
    isFree: false,
    popular: false,
    isCurrent: false,
    highlight: "Billed every 30 days",
  },
  {
    key: "ADVANCED_MONTHLY",
    name: "Advanced",
    description: "For growing stores with recurring catalog operations.",
    price: 50,
    compareAtPrice: null,
    features: [
      "Everything in Basic",
      "Recurring edits",
      "90-day bulk edit history",
      "5 inventory sync jobs",
      "5 scheduled exports",
      "5 automatic product rules",
      "1 code snippet",
    ],
    buttonText: "Choose Advanced",
    buttonVariant: "primary",
    isFree: false,
    popular: true,
    isCurrent: false,
    highlight: "Billed every 30 days",
  },
  {
    key: "PROFESSIONAL_MONTHLY",
    name: "Professional",
    description: "For teams managing high-volume catalog operations.",
    price: 110,
    compareAtPrice: null,
    features: [
      "Everything in Advanced",
      "Recurring edits",
      "180-day bulk edit history",
      "10 inventory sync jobs",
      "20 scheduled exports",
      "20 automatic product rules",
      "5 code snippets",
      "Priority support",
    ],
    buttonText: "Choose Pro",
    buttonVariant: "primary",
    isFree: false,
    popular: false,
    isCurrent: false,
    highlight: "Billed every 30 days",
  },
]);

export function getDefaultPricingPlans() {
  return DEFAULT_PRICING_PLANS.map((plan) => ({ ...plan, features: [...plan.features] }));
}
