export const translatedEditHistoryStatuses = {
  pending: {
    en: "Pending",
    de: "Ausstehend",
    fr: "En attente",
    es: "Pendiente",
    ar: "قيد الانتظار",
    hi: "लंबित",
    zh: "待定",
    ja: "保留中",
    ko: "보류 중",
    pt: "Pendente",
    ru: "В ожидании",
  },
  processing: {
    en: "Processing",
    de: "Verarbeitung",
    fr: "Traitement",
    es: "Procesando",
    ar: "جارٍ المعالجة",
    hi: "प्रसंस्करण",
    zh: "处理中",
    ja: "処理中",
    ko: "처리 중",
    pt: "Processando",
    ru: "Обработка",
  },
  completed: {
    en: "Completed",
    de: "Abgeschlossen",
    fr: "Terminé",
    es: "Completado",
    ar: "مكتمل",
    hi: "पूर्ण",
    zh: "已完成",
    ja: "完了",
    ko: "완료됨",
    pt: "Concluído",
    ru: "Завершено",
  },
  failed: {
    en: "Failed",
    de: "Fehlgeschlagen",
    fr: "Échoué",
    es: "Fallado",
    ar: "فشل",
    hi: "विफल",
    zh: "失败",
    ja: "失敗した",
    ko: "실패",
    pt: "Falhou",
    ru: "Неудачно",
  },
  Scheduled: {
    en: "Scheduled",
    de: "Geplant",
    fr: "Planifié",
    es: "Programado",
    ar: "مجدول",
    hi: "अनुसूचित",
    zh: "已安排",
    ja: "予定済み",
    ko: "예정됨",
    pt: "Agendado",
    ru: "Запланировано",
  },
  "Undo pending": {
    en: "Undo pending",
    de: "Rückgängig ausstehend",
    fr: "Annulation en attente",
    es: "Deshacer pendiente",
    ar: "في انتظار التراجع",
    hi: "पूर्ववत लंबित",
    zh: "撤消待定",
    ja: "元に戻す保留中",
    ko: "실행 취소 보류 중",
    pt: "Desfazer pendente",
    ru: "Ожидание отмены",
  },
  "Undo processing": {
    en: "Undo processing",
    de: "Rückgängig Verarbeitung",
    fr: "Annulation en cours",
    es: "Deshacer en proceso",
    ar: "جارٍ التراجع",
    hi: "पूर्ववत प्रसंस्करण",
    zh: "撤消处理中",
    ja: "元に戻す処理中",
    ko: "실행 취소 처리 중",
    pt: "Desfazer processando",
    ru: "Отмена обработки",
  },
  "Undo completed": {
    en: "Undo completed",
    de: "Rückgängig abgeschlossen",
    fr: "Annulation terminée",
    es: "Deshacer completado",
    ar: "تم التراجع",
    hi: "पूर्ववत पूर्ण",
    zh: "撤消完成",
    ja: "元に戻す完了",
    ko: "실행 취소 완료됨",
    pt: "Desfazer concluído",
    ru: "Отмена завершена",
  },
};

export const FIELD_TRANSLATIONS = {
  price: {
    en: "Price",
    de: "Preis",
    fr: "Prix",
    es: "Precio",
    ar: "السعر",
    hi: "कीमत",
    zh: "价格",
    ja: "価格",
    ko: "가격",
    pt: "Preço",
    ru: "Цена",
  },
  description: {
    en: "Description",
    de: "Beschreibung",
    fr: "Description",
    es: "Descripción",
    ar: "الوصف",
    hi: "विवरण",
    zh: "描述",
    ja: "説明",
    ko: "설명",
    pt: "Descrição",
    ru: "Описание",
  },
  category: {
    en: "Category",
    de: "Kategorie",
    fr: "Catégorie",
    es: "Categoría",
    ar: "الفئة",
    hi: "श्रेणी",
    zh: "类别",
    ja: "カテゴリー",
    ko: "카테고리",
    pt: "Categoria",
    ru: "Категория",
  },
  collections: {
    en: "Collections",
    de: "Kollektionen",
    fr: "Collections",
    es: "Colecciones",
    ar: "المجموعات",
    hi: "संग्रह",
    zh: "系列",
    ja: "コレクション",
    ko: "컬렉션",
    pt: "Coleções",
    ru: "Коллекции",
  },
  option1Name: {
    en: "Option 1 Name",
    de: "Optionsname 1",
    fr: "Nom de l’option 1",
    es: "Nombre de la opción 1",
    ar: "اسم الخيار 1",
    hi: "विकल्प 1 का नाम",
    zh: "选项 1 名称",
    ja: "オプション1の名前",
    ko: "옵션 1 이름",
    pt: "Nome da opção 1",
    ru: "Название опции 1",
  },
  option2Name: {
    en: "Option 2 Name",
    de: "Optionsname 2",
    fr: "Nom de l’option 2",
    es: "Nombre de la opción 2",
    ar: "اسم الخيار 2",
    hi: "विकल्प 2 का नाम",
    zh: "选项 2 名称",
    ja: "オプション2の名前",
    ko: "옵션 2 이름",
    pt: "Nome da opção 2",
    ru: "Название опции 2",
  },
  option3Name: {
    en: "Option 3 Name",
    de: "Optionsname 3",
    fr: "Nom de l’option 3",
    es: "Nombre de la opción 3",
    ar: "اسم الخيار 3",
    hi: "विकल्प 3 का नाम",
    zh: "选项 3 名称",
    ja: "オプション3の名前",
    ko: "옵션 3 이름",
    pt: "Nome da opção 3",
    ru: "Название опции 3",
  },
  option1Values: {
    en: "Option 1 Values",
    de: "Optionswerte 1",
    fr: "Valeurs de l’option 1",
    es: "Valores de la opción 1",
    ar: "قيم الخيار 1",
    hi: "विकल्प 1 के मान",
    zh: "选项 1 的值",
    ja: "オプション1の値",
    ko: "옵션 1 값",
    pt: "Valores da opção 1",
    ru: "Значения опции 1",
  },

  option2Values: {
    en: "Option 2 Values",
    de: "Optionswerte 2",
    fr: "Valeurs de l’option 2",
    es: "Valores de la opción 2",
    ar: "قيم الخيار 2",
    hi: "विकल्प 2 के मान",
    zh: "选项 2 的值",
    ja: "オプション2の値",
    ko: "옵션 2 값",
    pt: "Valores da opção 2",
    ru: "Значения опции 2",
  },

  option3Values: {
    en: "Option 3 Values",
    de: "Optionswerte 3",
    fr: "Valeurs de l’option 3",
    es: "Valores de la opción 3",
    ar: "قيم الخيار 3",
    hi: "विकल्प 3 के मान",
    zh: "选项 3 的值",
    ja: "オプション3の値",
    ko: "옵션 3 값",
    pt: "Valores da opção 3",
    ru: "Значения опции 3",
  },
  metaTitle: {
    en: "Meta Title",
    de: "Meta-Titel",
    fr: "Titre méta",
    es: "Título meta",
    ar: "عنوان الميتا",
    hi: "मेटा शीर्षक",
    zh: "元标题",
    ja: "メタタイトル",
    ko: "메타 제목",
    pt: "Título meta",
    ru: "Мета-заголовок",
  },

  metaDescription: {
    en: "Meta Description",
    de: "Meta-Beschreibung",
    fr: "Description méta",
    es: "Descripción meta",
    ar: "وصف الميتا",
    hi: "मेटा विवरण",
    zh: "元描述",
    ja: "メタディスクリプション",
    ko: "메타 설명",
    pt: "Descrição meta",
    ru: "Мета-описание",
  },

  taxable: {
    en: "Charge tax on this product",
    de: "Steuer auf dieses Produkt erheben",
    fr: "Appliquer la taxe sur ce produit",
    es: "Cobrar impuestos en este producto",
    ar: "فرض ضريبة على هذا المنتج",
    hi: "इस उत्पाद पर कर लागू करें",
    zh: "对此产品收税",
    ja: "この商品に税金を適用する",
    ko: "이 제품에 세금 적용",
    pt: "Cobrar imposto neste produto",
    ru: "Взимать налог с этого товара",
  },
  inventoryPolicy: {
    en: "Continue selling when out of stock",
    de: "Weiterverkaufen, wenn nicht auf Lager",
    fr: "Continuer à vendre en rupture de stock",
    es: "Seguir vendiendo cuando esté agotado",
    ar: "الاستمرار في البيع عند نفاد المخزون",
    hi: "स्टॉक खत्म होने पर भी बिक्री जारी रखें",
    zh: "缺货时继续销售",
    ja: "在庫切れでも販売を続ける",
    ko: "재고가 없어도 계속 판매",
    pt: "Continuar vendendo quando estiver sem estoque",
    ru: "Продолжать продавать при отсутствии товара",
  },
  compareAtPrice: {
    en: "Compare at price",
    de: "Vergleichspreis",
    fr: "Prix de comparaison",
    es: "Precio de comparación",
    ar: "سعر المقارنة",
    hi: "तुलनात्मक मूल्य",
    zh: "对比价格",
    ja: "比較価格",
    ko: "비교 가격",
    pt: "Preço de comparação",
    ru: "Сравнительная цена",
  },
  title: {
    en: "Title",
    de: "Titel",
    fr: "Titre",
    es: "Título",
    ar: "العنوان",
    hi: "शीर्षक",
    zh: "标题",
    ja: "タイトル",
    ko: "제목",
    pt: "Título",
    ru: "Заголовок",
  },
  deleteProducts: {
    en: "Delete products",
    de: "Produkte löschen",
    fr: "Supprimer les produits",
    es: "Eliminar productos",
    ar: "حذف المنتجات",
    hi: "उत्पाद हटाएं",
    zh: "删除产品",
    ja: "商品を削除",
    ko: "제품 삭제",
    pt: "Excluir produtos",
    ru: "Удалить товары",
  },
  vendor: {
    en: "Vendor",
    de: "Verkäufer",
    fr: "Vendeur",
    es: "Vendedor",
    ar: "البائع",
    hi: "विक्रेता",
    zh: "供应商",
    ja: "ベンダー",
    ko: "공급업체",
    pt: "Fornecedor",
    ru: "Поставщик",
  },
  handle: {
    en: "Handle",
    de: "Handle",
    fr: "Handle",
    es: "Handle",
    ar: "المُعرّف",
    hi: "हैंडल",
    zh: "句柄",
    ja: "ハンドル",
    ko: "핸들",
    pt: "Handle",
    ru: "Идентификатор",
  },
  productType: {
    en: "Product Type",
    de: "Produkttyp",
    fr: "Type de produit",
    es: "Tipo de producto",
    ar: "نوع المنتج",
    hi: "उत्पाद प्रकार",
    zh: "产品类型",
    ja: "製品タイプ",
    ko: "제품 유형",
    pt: "Tipo de Produto",
    ru: "Тип продукта",
  },
  barcode: {
    en: "Barcode",
    de: "Strichcode",
    fr: "Code-barres",
    es: "Código de barras",
    ar: "الباركود",
    hi: "बारकोड",
    zh: "条形码",
    ja: "バーコード",
    ko: "바코드",
    pt: "Código de barras",
    ru: "Штрихкод",
  },
  status: {
    en: "Status",
    de: "Status",
    fr: "Statut",
    es: "Estado",
    ar: "الحالة",
    hi: "स्थिति",
    zh: "状态",
    ja: "ステータス",
    ko: "상태",
    pt: "Status",
    ru: "Статус",
  },
  sku: {
    en: "SKU",
    de: "SKU",
    fr: "SKU",
    es: "SKU",
    ar: "SKU",
    hi: "SKU",
    zh: "SKU",
    ja: "SKU",
    ko: "SKU",
    pt: "SKU",
    ru: "SKU",
  },
  tags: {
    en: "Tags",
    de: "Stichwörter",
    fr: "Étiquettes",
    es: "Etiquetas",
    ar: "الوسوم",
    hi: "टैग",
    zh: "标签",
    ja: "タグ",
    ko: "태그",
    pt: "Tags",
    ru: "Теги",
  },
  csv: {
    en: "CSV",
    de: "CSV-Datei",
    fr: "Fichier CSV",
    es: "Archivo CSV",
    ar: "ملف CSV",
    hi: "CSV फ़ाइल",
    zh: "CSV 文件",
    ja: "CSVファイル",
    ko: "CSV 파일",
    pt: "Arquivo CSV",
    ru: "CSV файл",
  },
};

export const EDIT_TYPES = {
  "Manual edit": {
    en: "Manual Edit",
    de: "Manuelle Bearbeitung",
    fr: "Édition manuelle",
    es: "Edición manual",
    ar: "تعديل يدوي",
    hi: "मैनुअल संपादन",
    zh: "手动编辑",
    ja: "手動編集",
    ko: "수동 편집",
    pt: "Edição Manual",
    ru: "Ручное редактирование",
  },
  "Scheduled edit": {
    en: "Scheduled Edit",
    de: "Geplante Bearbeitung",
    fr: "Édition programmée",
    es: "Edición programada",
    ar: "تعديل مجدول",
    hi: "अनुसूचित संपादन",
    zh: "计划编辑",
    ja: "スケジュール編集",
    ko: "예약 편집",
    pt: "Edição Agendada",
    ru: "Запланированное редактирование",
  },
};

export const EXPORT_TYPES = {
  "Manual export": {
    en: "Manual Export",
    de: "Manueller Export",
    fr: "Exportation manuelle",
    es: "Exportación manual",
    ar: "تصدير يدوي",
    hi: "मैनुअल निर्यात",
    zh: "手动导出",
    ja: "手動エクスポート",
    ko: "수동 내보내기",
    pt: "Exportação Manual",
    ru: "Ручной экспорт",
  },

  "Scheduled export": {
    en: "Scheduled Export",
    de: "Geplanter Export",
    fr: "Exportation planifiée",
    es: "Exportación programada",
    ar: "تصدير مجدول",
    hi: "अनुसूचित निर्यात",
    zh: "计划导出",
    ja: "スケジュールされたエクスポート",
    ko: "예약 내보내기",
    pt: "Exportação Agendada",
    ru: "Запланированный экспорт",
  },
};

export const ProductFieldSynctranslations = {
  Collections: {
    en: "Collections",
    de: "Sammlungen",
    fr: "Collections",
    es: "Colecciones",
    ar: "المجموعات",
    hi: "संग्रह",
    zh: "系列",
    ja: "コレクション",
    ko: "컬렉션",
    pt: "Coleções",
    ru: "Коллекции",
  },
  "Product Types": {
    en: "Product Types",
    de: "Produkttypen",
    fr: "Types de produit",
    es: "Tipos de producto",
    ar: "أنواع المنتجات",
    hi: "उत्पाद प्रकार",
    zh: "产品类型",
    ja: "製品の種類",
    ko: "제품 유형",
    pt: "Tipos de Produto",
    ru: "Типы продуктов",
  },
  Products: {
    en: "Products",
    de: "Produkte",
    fr: "Produits",
    es: "Productos",
    ar: "المنتجات",
    hi: "उत्पाद",
    zh: "产品",
    ja: "製品",
    ko: "제품",
    pt: "Produtos",
    ru: "Продукты",
  },
};

export const BATCH_SIZE_FOR_EDIT = 75;
export const BATCH_SIZE_FOR_UNDO = 75;
